# Generated by Django 4.2.30 on 2026-09-13 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('ফ্লাইট', 'ফ্লাইট'), ('হোটেল', 'হোটেল'), ('ট্যুর', 'ট্যুর'), ('ট্রান্সফার', 'ট্রান্সফার')], max_length=50)),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='কনফার্মড', max_length=50)),
                ('status_color', models.CharField(default='bg-green-100 text-green-700', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('percent', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
    ]
