# Generated by Django 4.2.30 on 2026-09-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umrah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umrahpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='umrah/'),
        ),
    ]
